
export const BASELINE_SORT_BY_ALPHA_24PX=require("../assets/svg/baseline-sort_by_alpha-24px.png")
export const BASELINE_FORMAT_LIST_BULLETED_24PX=require("../assets/svg/baseline-format_list_bulleted-24px.png")
export const BASELINE_INFO_24PX=require("../assets/svg/baseline-info-24px.png")
export const BASELINE_CANCEL_24PX=require("../assets/svg/baseline-cancel-24px.png")
export const BASELINE_ARROW_FORWARD_IOS_24PX=require("../assets/svg/baseline-arrow_forward_ios-24px.png")
export const AUTORENEW_24PX=require("../assets/svg/autorenew-24px.png")
export const LINK_24PX=require("../assets/svg/link-24px.png")
export const CONTENT_COPY_24PX=require("../assets/svg/content_copy-24px.png")
export const BASELINE_SEARCH_24PX=require("../assets/svg/baseline-search-24px.png")
export const SLO=require("../assets/svg/slo.png")
export const DELETE_24PX=require("../assets/svg/delete-24px.png")
export const SHARE_24PX=require("../assets/svg/share-24px.png")
export const BASELINE_CLOSE_24PX=require("../assets/svg/baseline-close-24px.png")
