export enum Routes {
  EXAMPLE = "ROUTE_EXAMPLE",
  SEARCH_THESAURUS = "ROUTE_SEARCH_THESAURUS",
  SEARCH_COLLOCATIONS = "ROUTE_SEARCH_COLLOCATIONS",
  RANDOM = "ROUTE_RANDOM",
  INFO = "ROUTE_INFO",
}

export enum Stacks {
  EXAMPLE = "STACK_EXAMPLE",
  SEARCH_THESAURUS = "STACK_SEARCH_THESAURUS",
  SEARCH_COLLOCATIONS = "STACK_SEARCH_COLLOCATIONS",
  RANDOM = "STACK_RANDOM",
  INFO = "STACK_INFO",
}

export enum Params {
  SEARCH_STRING = "SEARCH_STRING",
}

export enum Params {}
